# Generated by Django 5.1.1 on 2024-10-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Mystery', 'Mystery'), ('Science', 'Science'), ('Fiction', 'Fiction'), ('Engineering', 'Engineering')], max_length=100)),
                ('first_published', models.DateTimeField(auto_now=True)),
                ('last_published', models.DateTimeField()),
            ],
        ),
    ]
